# Generated by Django 4.2.2 on 2023-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
